engines:
  radon:
    enabled: true
  pep8:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - python
ratings:
  paths:
    - "**.py"
exclude_paths:
  - fraudar/export
  - docs/
  - tests/
